name: Mostrar Data

on:
  push:
  workflow_dispatch:

jobs:
  mostrar-data:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir data e hora do Brasil
        run: |
          export TZ=America/Sao_Paulo
          echo "Data e hora (Brasil): $(date '+%d/%m/%Y %H:%M:%S')"
